name: Combine Files

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  combine:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Combine script examples
        shell: pwsh
        run: ./build/combine-files.ps1

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: script-examples
          path: ./script-examples.txt
